const uuid = require("uuid");

exports.inventory = [
    {
        id: uuid.v4(),
        name: "SHTANGA",
        isInGoodCondition: true,
        quantity: 15,
        weight: 20,
        producedBy: 'Nike',
    },
    {
        id: uuid.v4(),
        name: "SKAKALKA",
        isInGoodCondition: true,
        quantity: 12,
        weight: 0.1,
        producedBy: 'Xiaomi',
    },
    {
        id: uuid.v4(),
        name: "BLINY",
        isInGoodCondition: true,
        quantity: 40,
        weight: 10,
        producedBy: 'ROS IRON',
    },
    {
        id: uuid.v4(),
        name: "KOVRIK",
        isInGoodCondition: true,
        quantity: 40,
        weight: 10,
        producedBy: 'oCoo SHIVA',
    },
    {
        id: uuid.v4(),
        name: "KOVRIK",
        isInGoodCondition: true,
        quantity: 40,
        weight: 10,
        producedBy: 'oCoo SHIVA',
    },
    {
        id: uuid.v4(),
        name: "SKAKALKA",
        isInGoodCondition: true,
        quantity: 12,
        weight: 0.1,
        producedBy: 'Xiaomi',
    },
    {
        id: uuid.v4(),
        name: "BLINY",
        isInGoodCondition: true,
        quantity: 40,
        weight: 10,
        producedBy: 'ROS IRON',
    },
    {
        id: uuid.v4(),
        name: "KOVRIK",
        isInGoodCondition: true,
        quantity: 40,
        weight: 10,
        producedBy: 'oCoo SHIVA',
    },
    {
        id: uuid.v4(),
        name: "KOVRIK",
        isInGoodCondition: true,
        quantity: 40,
        weight: 10,
        producedBy: 'oCoo SHIVA',
    },
];